<?php
/**
 * TL_ROOT/system/modules/integrity_check/languages/ru/modules.php 
 * 
 * Contao extension: integrity_check 3.3.8 
 * Russian translation file 
 * 
 * Copyright : &copy; 2012..2016 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://contao.ninja 
 * Translator: Dmitri Kuznetsov (Kuzmich) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['integrity_check']['0'] = "Проверка целостности";
$GLOBALS['TL_LANG']['MOD']['integrity_check']['1'] = "Проверка целостности (Планировщик)";
