<?php
/**
 * TL_ROOT/system/modules/integrity_check/languages/ru/tl_integrity_check.php 
 * 
 * Contao extension: integrity_check 3.3.8 
 * Russian translation file 
 * 
 * Copyright : &copy; 2012..2015 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://contao.ninja 
 * Translator: Dmitri Kuznetsov (Kuzmich) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_integrity_check']['admin_email']                             = 'Отправить сообщение';
$GLOBALS['TL_LANG']['tl_integrity_check']['alternateemail']['0']                     = 'Альтернативный E-mail получателя';
$GLOBALS['TL_LANG']['tl_integrity_check']['alternateemail']['1']                     = 'Введите действительный E-mail адрес для отправки сообщений о проверках.';
$GLOBALS['TL_LANG']['tl_integrity_check']['alternateemail_legend']                   = 'Альтернативный E-mail адрес (не обязательно)';
$GLOBALS['TL_LANG']['tl_integrity_check']['check_debug']['0']                        = 'Отладка';
$GLOBALS['TL_LANG']['tl_integrity_check']['check_debug']['1']                        = 'Активировать режим отладки и расширенную регистрацию в системном журнале';
$GLOBALS['TL_LANG']['tl_integrity_check']['check_plans']['0']                        = 'План проверок';
$GLOBALS['TL_LANG']['tl_integrity_check']['check_plans']['1']                        = 'Планирование проверок и действий';
$GLOBALS['TL_LANG']['tl_integrity_check']['check_plans_expert']['0']                 = 'План проверок';
$GLOBALS['TL_LANG']['tl_integrity_check']['check_plans_expert']['1']                 = 'Планирование проверок и действий. При повторном выборе обновите отметки времени.';
$GLOBALS['TL_LANG']['tl_integrity_check']['check_title']['0']                        = 'Название';
$GLOBALS['TL_LANG']['tl_integrity_check']['check_title']['1']                        = 'Название проверки';
$GLOBALS['TL_LANG']['tl_integrity_check']['corrupt']                                 = 'Целостность файла %s: поврежден';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_action']['0']                          = 'Действие';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_action']['1']                          = 'Вид действия';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_file_status']                          = 'Статус';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_file_status_0']                        = 'непроверен';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_file_status_1']                        = 'в порядке';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_file_status_2']                        = 'поврежден';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_file_status_3']                        = 'Предупреждение';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_file_status_4']                        = 'Файл не найден';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_files']['0']                           = 'Файлы';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_files']['1']                           = 'Выберите файлы для проверки';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_interval']['0']                        = 'Время';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_interval']['1']                        = 'Время проверки';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_start_now_all']['0']                   = 'Запустить тест';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_start_now_all']['1']                   = 'Запустить тест';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_step_start_now']                       = 'Запустить тест';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_type_of_test']['0']                    = 'Идентификация';
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_type_of_test']['1']                    = 'Вид идентификации';
$GLOBALS['TL_LANG']['tl_integrity_check']['daily']                                   = 'ежедневно';
$GLOBALS['TL_LANG']['tl_integrity_check']['delete']['0']                             = 'Удалить проверку целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['delete']['1']                             = 'Удалить проверку целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['edit']['0']                               = 'Редактировать проверку целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['edit']['1']                               = 'Редактировать проверку целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['expert_legend']                           = 'Экспертные проверки';
$GLOBALS['TL_LANG']['tl_integrity_check']['file_not_found']                          = 'Целостность файла %s: не найден';
$GLOBALS['TL_LANG']['tl_integrity_check']['finished']                                = 'Проверка файлов на целостность завершена.';
$GLOBALS['TL_LANG']['tl_integrity_check']['hourly']                                  = 'ежечасно';
$GLOBALS['TL_LANG']['tl_integrity_check']['init']['0']                               = 'Новая проверка целостности по умолчанию';
$GLOBALS['TL_LANG']['tl_integrity_check']['init']['1']                               = 'Добавить новую проверку целостности по умолчанию всех 4 файлов.';
$GLOBALS['TL_LANG']['tl_integrity_check']['initConfirm']                             = 'Добавить новую проверку целостности по умолчанию всех 4 файлов?';
$GLOBALS['TL_LANG']['tl_integrity_check']['init_confirm_message']                    = 'Создана проверка целостности. Измените и/или активируйте её.';
$GLOBALS['TL_LANG']['tl_integrity_check']['install_count_check']['0']                = 'Проверить блокировку мастера установки';
$GLOBALS['TL_LANG']['tl_integrity_check']['install_count_check']['1']                = 'Если мастер установки заблокирован после трехкратного ввода неверного пароля, отправить Email администратору.';
$GLOBALS['TL_LANG']['tl_integrity_check']['log_blocked']                             = 'Запись в системном журнале о целостности файла %s не выполнена.(заблокировано)';
$GLOBALS['TL_LANG']['tl_integrity_check']['mail_blocked']                            = 'Сообщение о целостности файла %s не было отправлено. (заблокировано)';
$GLOBALS['TL_LANG']['tl_integrity_check']['maintenance_mode']                        = 'Страница технического обслуживания';
$GLOBALS['TL_LANG']['tl_integrity_check']['md5']                                     = 'MD5';
$GLOBALS['TL_LANG']['tl_integrity_check']['md5_blocked']                             = 'Проверка целостности файла %s не выполнена.(Отсутствуют контрольные суммы. Необходимо обновление!)';
$GLOBALS['TL_LANG']['tl_integrity_check']['message_1']                               = 'Проверка целостности %s обнаружила поврежденные файлы:';
$GLOBALS['TL_LANG']['tl_integrity_check']['message_2']                               = 'Эту информацию также можно найти в системном журнале.';
$GLOBALS['TL_LANG']['tl_integrity_check']['message_3']                               = 'Проверка целостности для %s не найдены MD5 контрольные суммы. Необходимо обновление.';
$GLOBALS['TL_LANG']['tl_integrity_check']['message_4']                               = 'Доступно обновление Contao %s. Новая версия: %s, Установленая версия: %s';
$GLOBALS['TL_LANG']['tl_integrity_check']['message_5']                               = 'Проверка целостности %s обнаружила, что мастер установки был заблокирован после того, как был введен неверный пароль, более чем три раза подряд.';
$GLOBALS['TL_LANG']['tl_integrity_check']['minutely']                                = 'ежеминутно';
$GLOBALS['TL_LANG']['tl_integrity_check']['monthly']                                 = 'ежемесячно';
$GLOBALS['TL_LANG']['tl_integrity_check']['new']['0']                                = 'Новая проверка целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['new']['1']                                = 'Добавить новую проверку целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['ok']                                      = 'Целостность файла %s: в порядке';
$GLOBALS['TL_LANG']['tl_integrity_check']['only_logging']                            = 'Журналировать';
$GLOBALS['TL_LANG']['tl_integrity_check']['publish_legend']                          = 'Настройки публикации';
$GLOBALS['TL_LANG']['tl_integrity_check']['published']['0']                          = 'Активировать проверку целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['published']['1']                          = 'Активация проверки целостности.';
$GLOBALS['TL_LANG']['tl_integrity_check']['refresh']['0']                            = 'Обновить отметку времени';
$GLOBALS['TL_LANG']['tl_integrity_check']['refresh']['1']                            = 'Обновить отметку времени для файла.';
$GLOBALS['TL_LANG']['tl_integrity_check']['refreshConfirm']                          = 'Обновить отметки времени файлов? Старые отметки будут перезаписаны.';
$GLOBALS['TL_LANG']['tl_integrity_check']['refresh_confirm_message']                 = 'Отметки времени были обновлены.';
$GLOBALS['TL_LANG']['tl_integrity_check']['restore']                                 = 'Восстановить';
$GLOBALS['TL_LANG']['tl_integrity_check']['show']['0']                               = 'Детали проверки целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['show']['1']                               = 'Детали проверки целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['subject']                                 = 'Contao :: Проверка целостности %s';
$GLOBALS['TL_LANG']['tl_integrity_check']['timestamp']                               = 'Отметка времени';
$GLOBALS['TL_LANG']['tl_integrity_check']['timestamp_not_found']                     = 'Целостность файла %s: не найдена отметка времени';
$GLOBALS['TL_LANG']['tl_integrity_check']['toggle']['0']                             = 'Активировать/деактивировать проверку целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['toggle']['1']                             = 'Активировать/деактивировать проверку целостности';
$GLOBALS['TL_LANG']['tl_integrity_check']['update_check']['0']                       = 'Проверить новые версии Contao';
$GLOBALS['TL_LANG']['tl_integrity_check']['update_check']['1']                       = 'Если доступна новая версия Contao (Minor/Bugfix), отправить Email администратору.';
$GLOBALS['TL_LANG']['tl_integrity_check']['update_check_contao_installed']           = 'Установленная версия Contao';
$GLOBALS['TL_LANG']['tl_integrity_check']['update_check_contao_latest']              = 'Последняя версия Contao';
$GLOBALS['TL_LANG']['tl_integrity_check']['update_check_contao_latest_not_detected'] = 'Последняя версия Contao не обнаружена.';
$GLOBALS['TL_LANG']['tl_integrity_check']['update_check_deactivated']                = 'Проверка на новых версий Contao деактивирована.';
$GLOBALS['TL_LANG']['tl_integrity_check']['weekly']                                  = 'еженедельно';

