<?php
/**
 * TL_ROOT/system/modules/integrity_check/languages/fa/modules.php 
 * 
 * Contao extension: integrity_check 3.3.2 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2012..2014 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['integrity_check']['0'] = "بررسی درستی";
$GLOBALS['TL_LANG']['MOD']['integrity_check']['1'] = "بررسی درستی (کرون)";
 
