<?php
/**
 * TL_ROOT/system/modules/integrity_check/languages/fa/tl_integrity_check.php 
 * 
 * Contao extension: integrity_check 3.3.2 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2012..2015 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://contao.ninja 
 * Translator: Hamid Abbaszadeh (respinar), http://contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_integrity_check']['ok'] = "وضعیت بررسی برای پرونده %s: بسیارخوب";
$GLOBALS['TL_LANG']['tl_integrity_check']['corrupt'] = "وضعیت بررسی برای پرونده %s: خراب";
$GLOBALS['TL_LANG']['tl_integrity_check']['finished'] = "بررسی پرونده‌ها برای درستی کامل شد.";
$GLOBALS['TL_LANG']['tl_integrity_check']['subject'] = "کانتائو :: بررسی درستی برای %s";
$GLOBALS['TL_LANG']['tl_integrity_check']['new']['0'] = "بررسی درستی جدید";
$GLOBALS['TL_LANG']['tl_integrity_check']['new']['1'] = "افزودن یک بررسی درستی جدید";
$GLOBALS['TL_LANG']['tl_integrity_check']['edit']['0'] = "ویرایش بررسی درستی";
$GLOBALS['TL_LANG']['tl_integrity_check']['edit']['1'] = "ویرایش بررسی درستی";
$GLOBALS['TL_LANG']['tl_integrity_check']['delete']['0'] = "حذف بررسی درستی";
$GLOBALS['TL_LANG']['tl_integrity_check']['delete']['1'] = "حذف بررسی درستی";
$GLOBALS['TL_LANG']['tl_integrity_check']['show']['0'] = "جزئیات بررسی درستی";
$GLOBALS['TL_LANG']['tl_integrity_check']['show']['1'] = "جزئیات بررسی درستی";
$GLOBALS['TL_LANG']['tl_integrity_check']['toggle']['0'] = "فعال/غیرفعال کردن بررسی درستی";
$GLOBALS['TL_LANG']['tl_integrity_check']['toggle']['1'] = "فعال/غیرفعال کردن بررسی درستی";
$GLOBALS['TL_LANG']['tl_integrity_check']['refresh']['0'] = "بروزرسانی برچسب زمانی";
$GLOBALS['TL_LANG']['tl_integrity_check']['refresh']['1'] = "بروزرسانی برچسب زمانی پرونده‌ها.";
$GLOBALS['TL_LANG']['tl_integrity_check']['init']['0'] = "بررسی درستی پیش‌فرض جدید";
$GLOBALS['TL_LANG']['tl_integrity_check']['init']['1'] = "یک بررسی جدید پیش‌فرض با چهار پرونده اضافه می‌کند.";
$GLOBALS['TL_LANG']['tl_integrity_check']['check_title']['0'] = "عنوان";
$GLOBALS['TL_LANG']['tl_integrity_check']['check_title']['1'] = "عنوان برای خلاصه";
$GLOBALS['TL_LANG']['tl_integrity_check']['check_debug']['0'] = "عیب‌یابی";
$GLOBALS['TL_LANG']['tl_integrity_check']['check_plans']['0'] = "برنامه بررسی";
$GLOBALS['TL_LANG']['tl_integrity_check']['check_plans']['1'] = "برنامه‌ریزی بررسی و فعالیت‌ها";
$GLOBALS['TL_LANG']['tl_integrity_check']['published']['0'] = "فعال کردن بررسی درستی";
$GLOBALS['TL_LANG']['tl_integrity_check']['published']['1'] = "بررسی درستی را فعال می‌کند.";
$GLOBALS['TL_LANG']['tl_integrity_check']['alternateemail']['0'] = "آدرس ایمیل دریافت کننده دیگر";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_files']['0'] = "پرونده‌ها";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_files']['1'] = "انتخاب پرونده‌ها برای بررسی";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_interval']['0'] = "زمان";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_interval']['1'] = "زمان بررسی";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_type_of_test']['0'] = "شناسایی";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_type_of_test']['1'] = "نوع شناسایی";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_action']['0'] = "عمل";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_action']['1'] = "نوع عمل";
$GLOBALS['TL_LANG']['tl_integrity_check']['check_plans_expert']['0'] = "برنامه بررسی";
$GLOBALS['TL_LANG']['tl_integrity_check']['expert_legend'] = "بررسی‌های پیشرفته";
$GLOBALS['TL_LANG']['tl_integrity_check']['publish_legend'] = "تنظیمات انتشار";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_file_status'] = "وضعیت";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_file_status_0'] = "بررسی نشده";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_file_status_1'] = "بسیارخوب";
$GLOBALS['TL_LANG']['tl_integrity_check']['cp_file_status_2'] = "خراب";
$GLOBALS['TL_LANG']['tl_integrity_check']['minutely'] = "دقیقه‌ای";
$GLOBALS['TL_LANG']['tl_integrity_check']['hourly'] = "ساعتی";
$GLOBALS['TL_LANG']['tl_integrity_check']['daily'] = "روزانه";
$GLOBALS['TL_LANG']['tl_integrity_check']['weekly'] = "هفتگی";
$GLOBALS['TL_LANG']['tl_integrity_check']['monthly'] = "ماهانه";
$GLOBALS['TL_LANG']['tl_integrity_check']['md5'] = "ام‌دی۵";
$GLOBALS['TL_LANG']['tl_integrity_check']['only_logging'] = "گزارش سیستم";
$GLOBALS['TL_LANG']['tl_integrity_check']['restore'] = "بازگردانی";
$GLOBALS['TL_LANG']['tl_integrity_check']['maintenance_mode'] = "صفحه نگهداشت";
$GLOBALS['TL_LANG']['tl_integrity_check']['refresh_confirm_message'] = "برچسب زمانی بروزرسانی شد.";
 
