<?php
/**
 * TL_ROOT/system/modules/integrity_check/languages/pt/modules.php 
 * 
 * Portugiesisch translation file 
 * 
 * Copyright : &copy; 2012..2015 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://contao.ninja 
 * Translator: Luciano Sportelli (ciaobello), https://www.contao-community.de/member.php?4042-ciaobello 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MOD']['integrity_check']      = 'Integrity Check (CRON)';
$GLOBALS['TL_LANG']['MOD']['integrity_check']['0'] = 'Verificação de integridade';
$GLOBALS['TL_LANG']['MOD']['integrity_check']['1'] = 'Verificação de integridade (CRON)';

