<?php
/**
 * TL_ROOT/system/modules/integrity_check/languages/pt/tl_integrity_check.php 
 * 
 * Portugiesisch translation file 
 * 
 * Copyright : &copy; 2012..2015 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://contao.ninja 
 * Translator: Luciano Sportelli (ciaobello), https://www.contao-community.de/member.php?4042-ciaobello 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_integrity_check']['ok'] = "Status de integridade de arquivo %s é: OK";
$GLOBALS['TL_LANG']['tl_integrity_check']['corrupt'] = "Status de integridade de arquivo %s é: Corrompido";
$GLOBALS['TL_LANG']['tl_integrity_check']['finished'] = "Verificação de integridade está terminado.";
$GLOBALS['TL_LANG']['tl_integrity_check']['subject'] = "Contao :: Verificação de integridade para %s";
$GLOBALS['TL_LANG']['tl_integrity_check']['message_1'] = "A verificação de integridade para %s encontrou arquivos corrompidos:";
$GLOBALS['TL_LANG']['tl_integrity_check']['message_2'] = "Esta informação também pode ser encontrados no log do sistema.";
